_commit: v2.1.3
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
dist_name: mopidy-scrobbler
ext_name: scrobbler
github_username: mopidy
short_description: Mopidy extension for scrobbling played tracks to Last.fm
